name: ask_ui_bridge
description: Local bridge server and launcher for Ask UI.
version: 0.0.1
repository: https://github.com/drown0315/ask_ui
homepage: https://github.com/drown0315/ask_ui

executables:
  ask_ui_bridge: ask_ui_bridge

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  vm_service: ^14.3.1

dev_dependencies:
  file_testkit: 1.0.0
  test: 1.25.8
